const fs = require('fs');
const p = 'app/api/bgm/route.ts';
let s = fs.readFileSync(p, 'utf-8');
const old = '    const results: BgmItem[] = [];';
const upd = '    const results: BgmItem[] = []; let searchDebug: any = undefined;';
s = s.replace(old, upd);
const old2 = '      results.push(...await searchCcmixter(query, limit));';
const upd2 = '      try { results.push(...await searchCcmixter(query, limit)); } catch (e:any) { searchDebug = e?.message || String(e); }';
s = s.replace(old2, upd2);
fs.writeFileSync(p, s, 'utf-8');
console.log('catch-search');
